### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by barisutagensen** [barisutagensen/protospace-37150#1]
# URL
https://protospace-37150.herokuapp.com/

**Comment by snkw-works** [comment]
@barisutagensen さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移するよう修正しましょう**
プロトタイプ名をクリックしても、詳細ページに遷移できない状態です。
<img width="488" alt="スクリーンショット_2022-01-23_16_04_40" src="https://user-images.githubusercontent.com/54050089/150668293-a9e6f36d-22a6-4966-a9a9-9802d809303b.png">


- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるよう修正しましょう**
ユーザー名が一部正しく表示されていない状態です。
<img width="1439" alt="スクリーンショット_2022-01-23_16_02_05" src="https://user-images.githubusercontent.com/54050089/150668229-c8b7322a-707d-415b-8e6b-9b0b0a685010.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by barisutagensen** [comment]
確認ありがとうございます！
修正して再度提出します。

**Comment by snkw-works** [comment]
@barisutagensen さん、お待たせいたしました。修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by barisutagensen** [comment]
@snkw-works さん、確認ありがとうございます！
最終課題に進みます。
